image: jupyter/base-notebook:latest

stages:
  - build

convert_to_markdown:
  stage: build
  script:
    - pip install nbconvert
    - for notebook in *.ipynb; do jupyter nbconvert --to markdown "$notebook"; done
  artifacts:
    paths:
      - "*.md"
      - "*/"
    expire_in: 1 week

