name: "Convert jupyter Notebooks to Markdown"

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert notebooks to Markdown
      run: |
        for notebook in *.ipynb; do
          jupyter nbconvert --to markdown "$notebook"
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Convert Jupyter notebooks to Markdown"
          git push origin HEAD:${{ github.ref }}
        fi

